### ISSUE TITLE
NSForwarding: does not implement methodSignatureForSelector - trouble ahead Unrecognized selector

### ISSUE THREAD

**Issue by nicholas12345** [3IE/swift-cache-manager#1]
While giving a try this fine piece of code for caching, I stumbled upon this message during execution:
"NSForwarding: does not implement methodSignatureForSelector - trouble ahead Unrecognized selector". After a bit of research, it appears that for most worked setting your class dependency NSObject, which clearly this code has. Did you have a similar problem? Maybe you can expand example with buttons to read and write in cache, maybe I am missing something. 
Thanks!

**Comment by nicholas12345** [comment]
Ignore it, my class wasn't implemented as NSObject subclass

**Comment by BenoitVerdier** [comment]
Ok. Yeah, this method is only for objets that inherit from NSObject (which is not mandatory in swift)
